image:
  repository: bgants/eurekaserver
  name: eurekaserver
  pullPolicy: Always

replicaCount: 1

serviceAccount:
  name: default

probes:
  liveness:
    type: tcpSocket
    initialDelaySeconds: 60
    periodSeconds: 20
    failureThreshold: 10
    timeoutSeconds: 1
  readiness:
    type: tcpSocket
    initialDelaySeconds: 60
    periodSeconds: 20
    failureThreshold: 10
    timeoutSeconds: 1

service:
  type: ClusterIP
  name: eurekaserver
  port: 8070
