image:
  repository: bgants/activemq
  name: activemq
  pullPolicy: IfNotPresent

replicaCount: 1

serviceAccount:
  name: default

probes:
  liveness:
    type: tcpSocket
    initialDelaySeconds: 60
    periodSeconds: 20
    failureThreshold: 10
    timeoutSeconds: 1
  readiness:
    type: tcpSocket
    initialDelaySeconds: 60
    periodSeconds: 20
    failureThreshold: 10
    timeoutSeconds: 1

service:
  type: ClusterIP
  nio:
    name: nio
    port: 8161
  pcmd:
    name: pcmd
    port: 61616
  stomp:
    name: stomp
    port: 61613
  xmpp:
    name: xmpp
    port: 5222
  webgui:
    name: webgui
    port: 8082
