spring:
  datasource:
    url: jdbc:postgresql://postgress:5432/rgm
    username: rgmuser
    password: pass123
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      ddl-auto: create-drop
    temp:
      use_jdbc_metadata_defaults: false
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  activemq:
    in-memory: false
    broker-url: tcp://activemq:61616
  jms:
    template:
      default-destination: rgm.queue
