server:
  port: 8070
eureka:
  instance:
    hostname: eurekaserver
  client:
    registerWithEurka: false
    fetchRegistry: false
    service-url:
      defaultZone: ${eureka.instance.hostname}:${server.port}/eureka/
  server:
      waitTimeInMsWhenSYncEmpty: 5


