image:
  repository: bgants/alpha-service
  name: alpha-service
  pullPolicy: Always

replicaCount: 1

serviceAccount:
  name: default

probes:
  liveness:
    type: tcpSocket
    initialDelaySeconds: 60
    periodSeconds: 20
    failureThreshold: 10
    timeoutSeconds: 1
  readiness:
    type: tcpSocket
    initialDelaySeconds: 60
    periodSeconds: 20
    failureThreshold: 10
    timeoutSeconds: 1

service:
  type: NodePort 
  name: alpha-service
  port: 8080

ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  hosts: 
   - host: sirus 
     paths:
        - /alpha(/|$)(.*)
