{{- define "common.deployment" -}}
{{- $common := dict "Values" .Values.common -}} 
{{- $noCommon := omit .Values "common" -}} 
{{- $overrides := dict "Values" $noCommon -}} 
{{- $noValues := omit . "Values" -}} 
{{- with merge $noValues $overrides $common -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "common.fullname" . }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "common.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "common.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "common.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}
        {{- if .Values.env -}}
         {{- include "common.env" . | nindent 10 }}
        {{- end }}
        {{- if .Values.envFrom -}}
         {{- include "common.envFrom" . | nindent 10 }}
        {{- end }}
        {{- if .Values.args -}}
         {{- include "common.args" . | nindent 10 }}
        {{- end }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
        {{- if .Values.probes.liveness.enabled }}
          livenessProbe:
            {{- include "common.livenessProbe" . | nindent 12 }}
        {{- end }}
        {{- if .Values.probes.readiness.enabled }}
            {{- include "common.readinessProbe" . | nindent 12 }}
          readinessProbe:
        {{- end }}
{{- end }}
{{- end }}
