apiVersion: v2
name: postgress
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: latest 
dependencies:
- name: common
  version: 0.1.0
  repository: file://../common
